### ISSUE TITLE
Server watchdog from frontend

### ISSUE THREAD

**Issue by davidrizo** [HISPAMUS/muret#44]
When classification server is not connected, the frontend fails and shows the user an incomprehensible error message (see image).

Better than waiting for the frontend to invoke the sever, a watchdog api rest should be created that could be invoked in a regular basis in order to check the health of the server.

![image](https://user-images.githubusercontent.com/10772049/67030823-8387da00-f110-11e9-900d-95ebdb8abdcd.png)

**Comment by antoniorv6** [comment]
Watchdog implemented and working correctly.
Every minute checks if the classification server is up.
It can receive a HTTP Exception (sth wrong going on in the server) or a RejectedConnectionException (if the server is dead and it cannot communicate).
If something of these happen, an email notification is sent to my personal email (need to change this to notify both administrators).
I am currently using a Mailjet free account (very useful for this tasks).
Need to create a HISPAMUS developers mail account, because it now fires mail errors with my second personal account.

Pushed refs to develop (With usermanager content in it, didn't have branch conflicts)
