### ISSUE TITLE
Document Analysis usability improvements

### ISSUE THREAD

**Issue by antoniorv6** [HISPAMUS/muret#77]
- Blue color in link.
- Change the format of region selection to the same list format as we have during edition.
- Last part didn't understand well, waiting for more instructions.

**Comment by davidrizo** [comment]
Cannot create a new page because:
- user draws the rectangle bounding the page
- the system creates an "undefined" region type
- when trying to change it to page, the system is limited to avoid setting a region to a page

![image](https://user-images.githubusercontent.com/10772049/70255337-eac42100-1786-11ea-93ab-5acae815042d.png)

The proposed workflow is:
- when the user creates a region, the default value should be "staff"
- the region type bar should be shown the same way it is shown on editing mode
![image](https://user-images.githubusercontent.com/10772049/70255830-aa18d780-1787-11ea-81fc-187b2d5df5db.png)
- when the user enters in the document analysis, if no region is found, the user should be asked if he wants to create a new pages and if so, for how many pages the image contains. If the number of pages is 1, the system should create a region of type page enclosing the whole page. If the number is 2 the system should split the image into two horizontal equally sized pages. If the number is > 2, the system should not create any

**Comment by antoniorv6** [comment]
Implemented usability changes. Found two problems:
 - Don't know why, the creation nav doesn't highlight the default selected option when opening.
 - Second problem is defined in other issue
