### ISSUE TITLE
DialogService with dropdown

### ISSUE THREAD

**Issue by davidrizo** [HISPAMUS/muret#91]
The same way we have a showInput method in DialogsService for making easier the creation of input dialogs, we need another one named showOptions that allows to choose between a list of options.
This method should show a dropDown with the options provided as parameter to the method.
It should have the possibility (optionally) of inputting a new element not provided in the list.

**Comment by antoniorv6** [comment]
I have developed a solution that satisfies the requirements in the issue. However, i will explain the steps to  use it propperly.
I have defined a new class to manage data in this modal:
`export class ModalOptions
{
  id:string;
  name:string;
}`
And defined a new function in Dialogs Service:
`public showOptions(title: string, options: ModalOptions[]): Observable<ModalOptions>`
In order to make the dialog work propperly, you have to pass a title and an array of ModalOption objects. If everything has been defined correctly, the dialog shows this:
![72d172aa62d3a68e8a399124470b7b4e](https://user-images.githubusercontent.com/36246417/71106223-3e8b2d00-21bf-11ea-82b4-e1a67dae7890.png)
The user can choose all the options you have passed to the function and also select a "Other" option, which will allow him to type the name of the option he wants to specify:
![de4f0b070a451b2e9c7008af946cc611](https://user-images.githubusercontent.com/36246417/71106308-709c8f00-21bf-11ea-984b-abac1e152049.png)

The function returns a ModalOptions Observable, so the result has to be catched as a ModalOptions type. If the chosen option belongs to the defined array, the object will contain the ID and the Name of it. If it has been defined by the user with the "Other" option, it will return an object with a **null ID** and the specified name.
