### ISSUE TITLE
Add automatic document analysis button (with dropdown to select classifier)

### ISSUE THREAD

**Issue by davidrizo** [HISPAMUS/muret#95]

**Comment by davidrizo** [comment]
The three layers must be developed:
- angular
- spring
- python classifier backend

We should be able to select the model to be used the same way we do in the agnostic representation

**Comment by antoniorv6** [comment]
TODO list:
- [ ] Develop document analysis models (Paco is responsible for this. Even tho I am developing my own autoencoders).
- [ ] Adapt Model Manager to handle the new models.
- [ ] Handle classification server request and return an array of bounding boxes  (attribute: [[xo, yo, xf, yf]])
- [ ] Handle spring request (just pass forward and generate the data Model)
- [ ] Send request and handle results in Angular (framework is done, should be simple to implement)

**Comment by antoniorv6** [comment]
Document Analysis mechanism is currently working on MuRet. It receives a request from the client and it returns an array of objects with the following structure (Specified in document-analysis/model/documentAnalysisModel.ts):
`export interface DocumentAnalysisModel
{
    staff?: BoundingBoxDA[]
}

export interface BoundingBoxDA
{
    x0: number,
    xf: number,
    y0: number,
    yf: number
}`
However, when the response is handled, the server triggers an error because no page exists. Even though, there is a page marked in the image with a null ID. 
My solution is to ask the user to tell how many pages does he want to create (should be 1 or 2 because if not, there will be no automation). Then, we create the new regions specified by the classifier's result.
